sudo: true
language: cpp

os:
  - linux

notifications:
  email: false

before_install:
  - df -h
  - cat /proc/mounts
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - mkdir ~/my-android-git
  - cd ~/my-android-git
  - repo init --depth 1 -u https://android.googlesource.com/platform/manifest -b ndk-r16 -q
  - repo sync -j16 -c --no-clone-bundle --no-tags

install:
  - df -h
  - cd ~/my-android-git
  - find -maxdepth 2
  - . build/envsetup.sh
  - lunch sdk-eng
  - make sdk

script:
  - cd ~/my-android-git
  - find

after_success:
  - echo hahaha
