sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
  apt:
    packages:
      - openssh-client
      - git

install:
  - echo "echo $KEYPASS" > /tmp/keypass
  - chmod +x /tmp/keypass
  - cp rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cd /tmp
  - SSH_ASKPASS=/tmp/keypass setsid git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git
  - cd vscode-build-travis
  - git checkout out

script:
  - find | tee out.txt
  - git add .
  - git commit -a -m 'hahaha'

after_success:
  - SSH_ASKPASS=/tmp/keypass setsid git push 
