sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
  apt:
    packages:
      - python
      - curl

before_install:
  - mkdir ~/bin
  - export PATH=~/bin:$PATH
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - mkdir ~/my-android-git
  - cd ~/my-android-git
  - repo init -u https://android.googlesource.com/platform/manifest -b master -g all,-notdefault,tools
  - repo sync

install:
  - cd ~/my-android-git
  - . build/envsetup.sh
  - lunch sdk-eng
  - make sdk

script:
  - cd ~/my-android-git
  - find

after_success:
  - echo hahaha
