sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
# apt:
#   packages:
#     - openssh-client
#     - git
#     - flatpak-builder

install:
  - curl -L https://github.com/flatpak/flatpak/releases/download/0.10.2.1/flatpak-0.10.2.1.tar.xz | tar -xJf -
  - curl -L https://github.com/flatpak/flatpak-builder/releases/download/0.10.6/flatpak-builder-0.10.6.tar.xz | tar -xJf -
  - cd ~/vscode-build-travis/flatpak-0.10.2.1
  - ./configure --help
  - ./configure
  - make
  - make install
  - cd ~/vscode-build-travis/flatpak-builder-0.10.6
  - ./configure --help
  - ./configure
  - make
  - make install  
  - flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  - flatpak install --user flathub org.freedesktop.Platform//1.6 org.freedesktop.Sdk//1.6
  - curl https://dl.winehq.org/wine/source/3.0/wine-3.0.tar.xz | tar -xJf -
  - cd wine-3.0
  - cat ./README
  - ./configure --help=recursive
  - ./configure
  - make
  - exit 1
  - echo '#!/bin/sh' > /tmp/keypass
  - echo "echo $KEYPASS" >> /tmp/keypass
  - export DISPLAY=:123
  - chmod +x /tmp/keypass
  - cp rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cd /tmp
  - SSH_ASKPASS=/tmp/keypass setsid git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git < /dev/null
  - cd vscode-build-travis
  - git checkout out

script:
  - find | tee out2.txt
  - git add .
  - git commit -a -m 'hahaha2'

after_success:
# - SSH_ASKPASS=/tmp/keypass setsid git push 
