sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - zip
      - libgtk2.0-0
      - libx11-dev
      - libxkbfile-dev
      - libsecret-1-dev
      - openssh-client
      - tar
      - xz-utils
      - jq

before_install:
  - echo '#!/bin/sh' > /tmp/keypass
  - echo "echo $KEYPASS" >> /tmp/keypass
  - chmod +x /tmp/keypass
  - git clone --depth 1 https://github.com/creationix/nvm.git ./.nvm
  - source ./.nvm/nvm.sh
  - nvm install 8.9.1
  - nvm use 8.9.1
  - npm install -g yarn
  - git clone --recursive -b '1.20.1' --single-branch --depth 1 https://github.com/Microsoft/vscode

install:
  - cd vscode
  - mv ./product.json ./product.json.bak
  - cat ./product.json.bak | jq '.extensionsGallery={"serviceUrl":"https://marketplace.visualstudio.com/_apis/public/gallery","cacheUrl":"https://vscode.blob.core.windows.net/gallery/index","itemUrl":"https://marketplace.visualstudio.com/items"}' | tee ./product.json
  - rm ./product.json.bak
  - yarn install --production --verbose

script:
  - node_modules/.bin/gulp vscode-linux-x64-min --max_old_space_size=4096

after_success:
  - cd ..
  - cp rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - SSH_ASKPASS=/tmp/keypass DISPLAY=:1 setsid git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git
  - cd vscode-build-travis
  - git checkout out
  - cd ..
  - tar -cJf vscode-build-travis/vscode-${TRAVIS_BUILD_NUMBER}.txz VSCode-linux-x64/
  - sha512sum vscode-build-travis/vscode-${TRAVIS_BUILD_NUMBER}.txz
  - cd vscode-build-travis
  - git add .
  - git commit -a -m vscode-${TRAVIS_BUILD_NUMBER}
  - SSH_ASKPASS=/tmp/keypass DISPLAY=:1 setsid git push
