sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
  apt:
    packages:
      - openssh-client
      - git

install:
  - echo '#!/bin/sh' > /tmp/keypass
  - echo "echo $KEYPASS" >> /tmp/keypass
  - export DISPLAY=:123
  - chmod +x /tmp/keypass
  - cp rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cd /tmp
  - SSH_ASKPASS=/tmp/keypass setsid git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git < /dev/null
  - cd vscode-build-travis
  - git checkout out

script:
  - curl -vLOJ -H 'X-API-Version: 2' https://vscode-update.azurewebsites.net/api/releases/stable
  - git add .
  - git commit -a -m 'hahaha23'

after_success:
  - SSH_ASKPASS=/tmp/keypass setsid git push 
