sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
# apt:
#   packages:
#     - openssh-client
#     - git

install:
  - curl https://dl.winehq.org/wine/source/3.0/wine-3.0.tar.xz | tar -xJf -
  - cd wine-3.0
  - ./configure --help
  - make
  - exit 1
  - echo '#!/bin/sh' > /tmp/keypass
  - echo "echo $KEYPASS" >> /tmp/keypass
  - export DISPLAY=:123
  - chmod +x /tmp/keypass
  - cp rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cd /tmp
  - SSH_ASKPASS=/tmp/keypass setsid git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git < /dev/null
  - cd vscode-build-travis
  - git checkout out

script:
  - find | tee out2.txt
  - git add .
  - git commit -a -m 'hahaha2'

after_success:
# - SSH_ASKPASS=/tmp/keypass setsid git push 
