sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
# apt:
#   packages:
#     - openssh-client
#     - git

install:
  - BASE=/home/travis/build/amtlib-dot-dll/vscode-build-travis
  - git clone --recursive https://github.com/zotero/zotero zotero-client
  - git clone --recursive https://github.com/zotero/zotero-build
  - git clone --recursive https://github.com/zotero/zotero-standalone-build
  - cd zotero-client
  - npm i
  - npm run build
  - cd ../zotero-standalone-build
# - ./scripts/check_requirements
  - ./fetch_xulrunner.sh -p l > /dev/null
  - ./fetch_pdftools
  - ./scripts/dir_build
  - cd /home/travis/build/amtlib-dot-dll/vscode-build-travis/zotero-build/xpi/build/staging
  - find
  - exit 1
  - echo '#!/bin/sh' > /tmp/keypass
  - echo "echo $KEYPASS" >> /tmp/keypass
  - export DISPLAY=:123
  - chmod +x /tmp/keypass
  - cp rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cd /tmp
  - SSH_ASKPASS=/tmp/keypass setsid git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git < /dev/null
  - cd vscode-build-travis
  - git checkout out

script:
  - find | tee out2.txt
  - git add .
  - git commit -a -m 'hahaha2'

after_success:
# - SSH_ASKPASS=/tmp/keypass setsid git push 
