sudo: true
language: cpp

os:
  - linux

notifications:
  email: false

addons:
  apt:
    packages:
      - python
      - curl
      - coreutils

before_install:
  - df -h
  - cat /proc/mounts
  - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
  - chmod a+x ~/bin/repo
  - mkdir ~/my-android-git
  - cd ~/my-android-git
  - repo init -u https://android.googlesource.com/platform/manifest -b android-8.0.0_r12 -g all,-notdefault,tools -q
  - repo sync -q > /dev/null

install:
  - cd ~/my-android-git
  - . build/envsetup.sh
  - lunch sdk-eng
  - make sdk

script:
  - cd ~/my-android-git
  - find

after_success:
  - echo hahaha
