sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
  apt:
    packages:
      - openssh-client
      - git

install:
  - cp rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - cd /tmp
  - git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git
  - cd vscode-build-travis
  - git checkout test

script:
  - find

after_success:
  - echo test
