sudo: false
language: cpp

os:
  - linux

notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - openssh
      - git

install:
  - cp rsa ~/.ssh/id_rsa
  - cd /tmp
  - git clone git@github.com:amtlib-dot-dll/vscode-build-travis.git
  - git checkout test

script:
  - find

after_success:
  - echo test
